import os

html = """
<!DOCTYPE html>
<html>
<head>
    <title>APIHawk Security Report</title>
    <style>
        body{
            font-family: Arial, sans-serif;
            background:#f4f4f4;
            margin:40px;
        }

        h1{
            color:#1f4e79;
        }

        table{
            width:100%;
            border-collapse:collapse;
            margin-top:20px;
        }

        th,td{
            border:1px solid #ccc;
            padding:10px;
            text-align:left;
        }

        th{
            background:#1f4e79;
            color:white;
        }

        .high{
            color:red;
            font-weight:bold;
        }

        .critical{
            color:darkred;
            font-weight:bold;
        }

        .low{
            color:green;
            font-weight:bold;
        }
    </style>
</head>

<body>

<h1>🦅 APIHawk Security Assessment Report</h1>

<h2>Summary</h2>

<ul>
<li>Total APIs : 6</li>
<li>Shadow APIs : 2</li>
<li>Sensitive APIs : 2</li>
<li>Overall Risk : HIGH</li>
</ul>

<h2>Detected Endpoints</h2>

<table>

<tr>
<th>Endpoint</th>
<th>Category</th>
<th>Risk</th>
</tr>

<tr>
<td>/login</td>
<td>Sensitive Endpoint</td>
<td class="high">HIGH</td>
</tr>

<tr>
<td>/admin/debug</td>
<td>Shadow API</td>
<td class="critical">CRITICAL</td>
</tr>

<tr>
<td>/patients</td>
<td>Normal API</td>
<td class="low">LOW</td>
</tr>

</table>

<h2>Recommendations</h2>

<ul>
<li>Remove undocumented APIs.</li>
<li>Protect sensitive endpoints.</li>
<li>Review authentication.</li>
<li>Keep Swagger documentation updated.</li>
</ul>

<hr>

<p><b>Generated by APIHawk v1.0</b></p>

</body>
</html>
"""

os.makedirs("reports", exist_ok=True)

with open("reports/security_report.html", "w", encoding="utf-8") as file:
    file.write(html)

print("=" * 50)
print("APIHAWK HTML REPORT GENERATOR")
print("=" * 50)
print("\nHTML report generated successfully.")
print("Saved to: reports/security_report.html")