from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from datetime import datetime
import os

# Create reports folder if it doesn't exist
os.makedirs("reports", exist_ok=True)

# PDF file path
pdf_path = "reports/security_report.pdf"

# Create PDF document
doc = SimpleDocTemplate(pdf_path)

styles = getSampleStyleSheet()
elements = []

# Title
title = Paragraph("<b><font size=20 color='darkblue'>🦅 APIHawk Security Assessment Report</font></b>", styles["Title"])
elements.append(title)
elements.append(Spacer(1, 20))

# Report information
date = datetime.now().strftime("%d %B %Y %I:%M %p")

elements.append(Paragraph(f"<b>Project:</b> Digital Health Gateway", styles["Normal"]))
elements.append(Paragraph(f"<b>Scan ID:</b> API-2026-001", styles["Normal"]))
elements.append(Paragraph(f"<b>Generated:</b> {date}", styles["Normal"]))
elements.append(Paragraph(f"<b>Version:</b> APIHawk v1.0", styles["Normal"]))
elements.append(Spacer(1, 20))

# Executive Summary
elements.append(Paragraph("<b>Executive Summary</b>", styles["Heading2"]))
elements.append(
    Paragraph(
        "APIHawk analyzed the API specification and identified Shadow APIs, "
        "Sensitive Endpoints, and overall HIGH security risk. "
        "Immediate review is recommended.",
        styles["BodyText"]
    )
)
elements.append(Spacer(1, 20))

# Statistics table
data = [
    ["Metric", "Value"],
    ["Total APIs", "6"],
    ["Shadow APIs", "2"],
    ["Sensitive APIs", "2"],
    ["Risk Level", "HIGH"],
]

table = Table(data, colWidths=[220, 150])

table.setStyle(TableStyle([
    ("BACKGROUND", (0,0), (-1,0), colors.darkblue),
    ("TEXTCOLOR", (0,0), (-1,0), colors.white),
    ("GRID", (0,0), (-1,-1), 1, colors.black),
    ("BACKGROUND", (0,1), (-1,-1), colors.beige),
    ("ALIGN", (0,0), (-1,-1), "CENTER"),
    ("FONTNAME", (0,0), (-1,0), "Helvetica-Bold"),
    ("BOTTOMPADDING", (0,0), (-1,0), 10),
]))

elements.append(table)
elements.append(Spacer(1, 20))

# Recommendations
elements.append(Paragraph("<b>Security Recommendations</b>", styles["Heading2"]))

recommendations = [
    "• Remove undocumented Shadow APIs.",
    "• Protect sensitive endpoints using strong authentication.",
    "• Enable API rate limiting.",
    "• Keep Swagger documentation updated.",
    "• Perform regular security assessments."
]

for rec in recommendations:
    elements.append(Paragraph(rec, styles["BodyText"]))

elements.append(Spacer(1, 20))

# Footer
elements.append(Paragraph("<b>Generated by APIHawk v1.0</b>", styles["Heading3"]))
elements.append(Paragraph("Developed by Sai Sandeep Gedela", styles["Normal"]))

# Build PDF
doc.build(elements)

print("=" * 60)
print("🦅 APIHAWK PDF REPORT GENERATOR")
print("=" * 60)
print("✅ PDF Report Generated Successfully")
print(f"📄 Saved to: {pdf_path}")